services:
  # Web Service (FastAPI)
  - type: web
    name: rss-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./scripts/start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: rss-db
          property: connectionString

      - key: REDIS_URL
        fromService:
          type: redis
          name: rss-redis
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: PROJECT_NAME
        value: "Personalized RSS Feed"

      - key: BACKEND_CORS_ORIGINS
        value: "*"


  # Background Worker (Celery)
  - type: worker
    name: rss-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./scripts/worker_start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: rss-db
          property: connectionString

      - key: REDIS_URL
        fromService:
          type: redis
          name: rss-redis
          property: connectionString

      - key: SECRET_KEY
        fromService:
          type: web
          name: rss-backend
          envVarKey: SECRET_KEY


  # Redis (Broker / Cache)
  - type: redis
    name: rss-redis
    plan: free # Optional: Explicitly state plan if needed
    ipAllowList: [] # internal only



databases:
  - name: rss-db
    databaseName: rss_feed
    user: rss_user
