services:
  - type: web
    name: rss-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./scripts/start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PROJECT_NAME
        value: "RSS API"
      - key: BACKEND_CORS_ORIGINS
        value: "*"
